core/urls.py
from django.conf.urls import url
from django.contrib import admin

from . import views

urlpatterns = [
    url(r'^pla/$', views.pla, name='pla'),
    url(r'^pla/edit/(?P<id>[0-9]+)$', views.pla_edit, name='edit'),
    url(r'^pla/get/(?P<c>[\w-]+)/(?P<id>[0-9]+)$', views.pla_get, name='get'),
    url(r'^pla/create/(?P<feed>[0-9]+)$', views.pla_create, name='create'),
    url(r'^pla/action/$', views.pla_action, name='pla_aciton'),
    url(r'^pla/delete/(?P<id>[0-9]+)$', views.pla_delete, name='delete'),
]

products/urls.py
from django.conf.urls import url
from django.contrib import admin

from . import views

urlpatterns = [
    #url(r'^$', views.index, name='index'),
    url(r'^c/(?P<link>[\w-]+)/(?P<id>[0-9]+)$', views.category, name='category'),
    url(r'^p/(?P<link>[\w-]+)/(?P<id>[0-9]+)$', views.product, name='product'),
    url(r'^handle/$', views.handle, name='product_handle'),
    url(r'^category/$',views.product_cateogry,name='category_product'),
    url(r'^show_hidden_on_out/$',views.show_hidden_on_out, name='show_hidden_on_out'),
    url(r'^search_attributes/$',views.search_attributes, name='search_attributes'),
    url(r'^render_options/$', views.render_options, name='product_render'),
    url(r'^report/$', views.report, name='product_report'),
    url(r'^tag_sku_view/(?P<id>[0-9]+)$',views.tag_sku_view, name='tag_sku_view'),
    url(r'^test/$', views.test, name='product_test'),
    url(r'^ajax_test/$', views.ajax_test, name='ajax_test'),
    url(r'^report_export/$', views.report_export, name='product_report_export'),
    url(r'^phone_product/$', views.phone_product, name='phone_product'),
    url(r'^product_sale/$', views.product_sale, name='product_sale'),
    url(r'^export_sku/$', views.export_sku, name='export_sku'),
    url(r'^sale_price_memcache/$', views.sale_price_memcache, name='sale_price_memcache'),

    #url(r'^c/(?P<link>\w+)/(?P<id>[0-9]+)$', views.collection, name='collection'),
    #url(r'^(?P<question_id>[0-9]+)/results/$', views.results, name='results'),
    #url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
]

project/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic import TemplateView
from django.conf import settings
from products import views as products_views
from orders import views as orders_views
from django.views import static
from carts.views import ProductAutocomplete,CelebritsAutocomplete,FilterAutocomplete,CategoryAllAutocomplete,ProductitemAutocomplete,CustomerCouponsAutocomplete

urlpatterns = [

    url(r'^$', products_views.index, name='index'),
    url(r'^product-autocomplete/$', ProductAutocomplete.as_view(), name='product-autocomplete'),
    url(r'^celebrits-autocomplete/$', CelebritsAutocomplete.as_view(), name='celebrits-autocomplete'),
    url(r'^filter-autocomplete/$', FilterAutocomplete.as_view(), name='filter-autocomplete'),
    url(r'^categoryAll-autocomplete/$', CategoryAllAutocomplete.as_view(), name='categoryAll-autocomplete'),
    url(r'^productitem-autocomplete/$', ProductitemAutocomplete.as_view(), name='productitem-autocomplete'),
    url(r'^CustomerCoupons-autocomplete/$', CustomerCouponsAutocomplete.as_view(), name='CustomerCoupons-autocomplete'),
    url(r'^products/', include('products.urls')),
    url(r'^core/', include('core.urls')),
    url(r'^orders/', include('orders.urls')),
    url(r'^accounts/', include('registration.backends.default.urls')),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^carts/', include('carts.urls')),
    url(r'^celebrities/', include('celebrities.urls')),
    url(r'^about/$', TemplateView.as_view(template_name="about.html")),
    url(r'^admin/', admin.site.urls),
    url(r'^dashboard/$', orders_views.dashboard, name='dashboard'),
    # url(r'^site_media/(?P<path>.*)$', 'django.views.static.serve',{'document_root': settings.STATIC_PATH}),
    url(r'^site_media/(?P<path>[\S]+)$', static.serve,{'document_root': settings.STATIC_PATH}),
]

products/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.http import HttpResponse
from django.db import models
from mptt.models import MPTTModel
from django.contrib import messages
import datetime,time
from django.db.models.signals import pre_save, post_save, m2m_changed
from django.contrib.auth.models import User
from django.shortcuts import render, get_object_or_404, redirect
from django.conf import settings
import uuid
from uuslug import slugify
import hashlib
import os
import itertools
from elasticsearch import Elasticsearch
from django.core.urlresolvers import reverse
from django_unixdatetimefield import UnixDateTimeField
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from django.utils.html import format_html
from celebrities.models import Celebrits
import carts
from core.views import eparse,nowtime,pp
import phpserialize
from django.db import connection, transaction
from django.conf import settings
import urllib
import urllib2
import json
# import sys, os
# reload(sys)
# sys.setdefaultencoding('utf-8')
import memcache
# from django.core.cache import cache


class OldProduct(models.Model):

    sku = models.CharField(max_length=100)
    status = models.BooleanField(default=True)

    def __unicode__(self):
        return self.sku


class Filter(models.Model):

    TYPE = (
            (0, u'Mulit Select'),
            (1, u'One Select'),
            (2, u'Input'),
        )

    type = models.IntegerField(choices=TYPE, default=0)
    name = models.CharField(max_length=100)
    options = models.TextField(blank=True, default="")
    required = models.BooleanField(default=False)

    def __unicode__(self):
        return self.options

    class Meta:
        verbose_name = u'产品过滤'
        verbose_name_plural = u'产品过滤'

class Collection(MPTTModel):
    name = models.CharField(max_length=100, verbose_name=u"分类名称")
    code = models.CharField(max_length=2, help_text=u"00-ZZ")
    parent = models.ForeignKey("self", blank=True, null=True, related_name="children", verbose_name=u"父级分类")
    brief = models.TextField(blank=True, verbose_name=u"分类简介")
    status = models.BooleanField(default=True)
    #filters = models.ManyToManyField(Filter, blank=True)

    created = UnixDateTimeField(auto_now_add=True, verbose_name=u"新增时间")
    updated = UnixDateTimeField(auto_now=True, verbose_name=u"修改时间")
    deleted = models.BooleanField(default=False, verbose_name=u"是否已删除")

   #class Meta:
   #    verbose_name = u'产品分类'
   #    verbose_name_plural = u'产品分类'

    def __unicode__(self):
        # return "%03d.%s" % (self.id, self.name)
        return self.name

    @property
    def link(self):
        return slugify(self.name)

    @models.permalink
    def get_absolute_url(self):
        return ('collection', (), {'id':self.id, "link":self.link,})


def get_image_upload_path(instance, filename):
    fn, ext = os.path.splitext(filename)
    if not ext:
        ext = '.jpg'
    #name = time.strftime('%y-%m/%d',time.localtime(time.time()))
    name = str(uuid.uuid4())
    return os.path.join('img', name[0:3], name[3:]+ext)

def get_product_image_upload_path(instance, filename):
    fn, ext = os.path.splitext(filename)
    if not ext:
        ext = '.jpg'
    image_id = instance.id
    if image_id:
        name = str(instance.id)+ext
    else:
        image = ProductImage.objects.all().order_by('-id').first()
        name = str(int(image.id)+int(1))+ext
    return '%s/%s' %('pimages/',name)

def get_celebrity_image_upload_path(instance, filename):
    fn, ext = os.path.splitext(filename)
    if not ext:
        ext = '.jpg'
    name = fn+ext
    return '%s/%s' %('simages/',name)

def get_category_image_upload_path(instance, filename):
    fn, ext = os.path.splitext(filename)
    if not ext:
        ext = '.jpg'
    name = fn+ext
    return '%s/%s' %('simages/',name)



class Category(MPTTModel):
    VISIBILITY = (
            (1,u"可见"),
            (0,u"不可见"),
        )

    ORDERBY = (
            (1,u"新增时间"),
            (2,u"购买次数"),
            (3,u"名称"),
            (4,u"价格"),
        )

    DESC = (
            (0,u"倒序"),
            (1,u"升序"),
        )

    STEREOTYPED = (
            (1,u"显示"),
            (0,u"隐藏"),
        )

    IS_BRAND = ON_MENU =(
            (1,u"是"),
            (0,u"否"),
        )

    name = models.CharField(max_length=255,default='', blank=True,null=True, verbose_name=u"分类名称")
    link = models.CharField(max_length=255, default='', verbose_name=u"URL")
    #code = models.CharField(max_length=2, help_text=u"00-ZZ")
    parent = models.ForeignKey("self", blank=True, null=True,related_name="children", verbose_name=u"父级分类")
    # status = models.BooleanField(default=True)
    filters = models.ManyToManyField(Filter, blank=True)
    
    orderby = models.CharField(max_length=100, default='',blank=True,null=True, verbose_name=u"Products order by")
    desc = models.IntegerField(choices=DESC, default=1, verbose_name=u"升/倒序")
    visibility = models.IntegerField(choices=VISIBILITY, default=1, verbose_name=u"是否可见")
    on_menu = models.IntegerField(choices=ON_MENU, default=1, verbose_name=u"Listed on menu")
    stereotyped = models.IntegerField(choices=STEREOTYPED, default=1, verbose_name=u"Stereotyped modules")
    # site_id = models.BooleanField(default=0)
    
    created = UnixDateTimeField(auto_now_add=True,blank=True,null=True, verbose_name=u"新增时间")
    updated = UnixDateTimeField(auto_now=True,blank=True,null=True, verbose_name=u"修改时间")
    deleted = models.BooleanField(default=False,blank=True, verbose_name=u"是否已删除")

    template = models.CharField(max_length=100, blank=True, verbose_name=u"分类模板")
    brief = models.TextField(blank=True, verbose_name=u"分类简介")
    description = models.TextField(blank=True,default='',null=True, verbose_name=u"分类描述")
    hot_catalog = models.TextField(blank=True,default='',null=True, verbose_name=u"hot catalog & link", help_text=u"格式：dresses,dresses-c-92")
    #position = models.IntegerField(default=0, verbose_name=u"排序")
    is_brand = models.IntegerField(choices=IS_BRAND, default=0, verbose_name=u"Is Brand")
    price_ranges = models.CharField(max_length=100, blank=True, verbose_name=u"Price Ranges", help_text=u"e.x: '5,7' means '(0,5],(5,7]' ") 

    meta_title = models.CharField(blank=True, max_length=100, default='', verbose_name=u"SEO标题")
    meta_keywords = models.TextField(blank=True,null=True,default='', verbose_name=u"SEO关键字")
    meta_description = models.TextField(blank=True,null=True, verbose_name=u"SEO描述")

    #max_count = models.IntegerField(default=0, help_text=u"分类中展示的最多产品数，影响前台分页的页数，为0则不限制")
    recommended_products = models.CharField(max_length=100, blank=True,default='', verbose_name=u"推荐产品sku", help_text="用','隔开，如：'CAAAFT2,BD000KTV,BD000KTX' ")
    image_src = models.ImageField(upload_to=get_category_image_upload_path, blank=True,default='',  verbose_name=u"图片地址")
    image_link = models.CharField(max_length=100, blank=True,default='', verbose_name=u"图片链接")
    image_alt = models.CharField(max_length=100, blank=True,default='', verbose_name=u"图片文本", help_text=u"图片无法显示时将用该文字代替")
    image_map = models.TextField(blank=True,default='', verbose_name=u"Image Map")
    pimage_src = models.ImageField(upload_to=get_category_image_upload_path,blank=True,default='', verbose_name=u"手机图片地址")
    position = models.IntegerField(default=0, verbose_name=u"排序")
    is_filter = models.IntegerField(default=0, verbose_name=u"是否有排序规则") 
    pimage_map = models.TextField(blank=True, default='', verbose_name=u"手机版Image Map")

    class Meta:
        verbose_name = u'分类'
        verbose_name_plural = u'分类'

    def __unicode__(self):
        # return "%03d.%s" % (self.id, self.name)
        return self.name

    @property
    def category_link(self):
        return slugify(self.name)

    @models.permalink
    def get_absolute_url(self):
        return ('category', (), {'id':self.id, "link":self.category_link,})

    """分类图片保存时去掉simages/,只保留图片名称"""
    def change_category_imagename(self,request):
        category = Category.objects.filter(id=self.id).first()
        if category:
            image_src = category.image_src
            pimage_src = category.pimage_src
            if image_src:
                image_src = str(image_src)
                if image_src.find('simages/') != -1:
                    index = image_src.find('simages/')+8
                    name = image_src[index:]
                    query = Category.objects.filter(id=self.id).update(image_src=name)
            if pimage_src:
                pimage_src = str(pimage_src)
                if pimage_src.find('simages/') != -1:
                    index = pimage_src.find('simages/')+8
                    name = pimage_src[index:]
                    query = Category.objects.filter(id=self.id).update(pimage_src=name)


    def es_index(self):
        es = Elasticsearch()
        _body= {
                "title": self.name,
                "brief": self.sku,
                "id": self.id,
                "url": self.get_absolute_url(),
        }
        res = es.index(index= settings.ES_INDEX, doc_type='category', id=self.id, body=_body)
        return res

    def es_delete(self):
        es = Elasticsearch()
        res = es.delete(index=settings.ES_INDEX, doc_type='category', id=self.id, ignore=[400, 404])
        return res

    # def cate_basic_save(self, request):
    #     if request.POST.get('type', '') == 'cate_basic_save':
    #         category_links = request.POST.get('category_links', '').strip().split('\r\n')
    #         print category_links
    #         category_linkarr = Category.objects.filter(category_link__in=category_links,deleted=0).values_list('id')

class CategorySorts(models.Model):

    category = models.ForeignKey(Category, verbose_name=u"分类名称")
    sort = models.CharField(default='',max_length=40,verbose_name="SKU")

products/forms.py
# -*- coding: utf-8 -*-
# from __future__ import unicode_literals
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext, ugettext_lazy as _
from django.conf import settings
from django import forms
from django.forms import ModelForm

from products.models import *
from dal import autocomplete

class CategoryProductForm(ModelForm):

    class Meta:
        model = CategoryProduct
        fields = '__all__'

        widgets = {
            'category': autocomplete.ModelSelect2(url='categoryAll-autocomplete'),
        }

products/templates/ajax_test.html
{% extends "base_header.html" %}
{% block content %}
{% include "cxcalendar.html" %}

<form method="post" id="formadd">
    {% csrf_token %}
    <input type="hidden" id="id_type" value="form001">
    <label for="id_name">用户名</label>
    <input type="text" id="id_name"/>
    <label for = "id_password">密码</label>
    <input type="password" id="id_password"/>
    <button type="submit" id="submit" >提交</button>
    <div id="result"></div>
</form>

<form id="form_date" method="post">
    {% csrf_token %}
    <input type="hidden" id="id_type2" value="onstock_vs_saled">
    <strong>时间范围：</strong><font size="2">(默认为最近7天，建议选择时间间隔不要过长)</font><br>
    <label class="control-label" for="fileInput">From:</label>
    <input type="text" class="date" id="from_time">
    <label class="control-label" for="fileInput">To:</label>
    <input type="text" class="date" id="to_time">
    <button type="submit" id="submit" class="btn btn-primary">sub</button><br>
    <div id="order_report" style="display: inline-block; margin: 0 auto"></div>
</form>

<br><br><br>

<form id="form_test" method="post">
    {% csrf_token %}
    <input type="hidden" id="hidden_test" value="hidden_test">
    <strong>时间范围：</strong><font size="2">(默认为最近7天，建议选择时间间隔不要过长)</font><br>
    <label class="control-label" for="fileInput">From:</label>
    <input type="text" class="date" id="test_from_time">
    <label class="control-label" for="fileInput">To:</label>
    <input type="text" class="date" id="test_to_time">
    <button type="submit" id="submit" class="btn btn-primary">sub</button><br>
    
</form>


<br><br><br>
<div id="test" style="height: 400px; min-width: 310px"></div>

<script>
    $(document).ready(function(){
        $.ajaxSetup({
             data: {csrfmiddlewaretoken: '{{ csrf_token }}' },
        });
        $('#formadd').submit(function(){
            var name = $("#id_name").val();                 //获得form中用户输入的name 注意这里的id_name 与你html中的id一致
            var password = $("#id_password").val();    //同上
            var type = $("#id_type").val();    //同上
           
            $.ajax({
                type:"POST",
                data: {type:type,name:name, password:password},
                url: "{% url 'ajax_test' %}", //后台处理函数的url 这里用的是static url 需要与urls.py中的name一致
                cache: false,
                dataType: "html",
                // contentType: "application/json; charset=utf-8",
                success: function(data, statues, xml){
                    data = $.parseJSON(data);
                    // alert(data.name);    
                    $('#result').html(data.name);                                     //成功时弹出view传回来的结果
                },
                error: function(){
                    alert("false");
                }
            });
            return false;
        });

        $('#form_date').submit(function(){
            var from_time = $("#from_time").val();
            var to_time = $("#to_time").val();
            var type = $("#id_type2").val();

            $.ajax({
                type: "POST",
                data: {type:type,from_time:from_time,to_time:to_time},
                url: "{% url 'ajax_test' %}",
                cache: false,
                dataType: "html",

                success: function(data,statues,xml){
                    data = $.parseJSON(data);
                    $('#result').html(data.from_time);
                    $('#order_report').highcharts({
                        chart: {
                        type: 'spline'
                        },
                        title: {
                            text: '上新产品数及上新产品的销量对比统计'
                        },
                        subtitle: {
                            text: ''
                        },
                        xAxis: {
                            type: 'datetime',
                            dateTimeLabelFormats: { // don't display the dummy year
                                month: '%e. %b',
                                year: '%b'
                            },
                            title: {
                                text: 'Date'
                            }
                        },
                        yAxis: {
                            title: {
                                text: '数量'
                            },
                            min: 0
                        },
                        tooltip: {
                            headerFormat: '<b>{series.name}</b><br>',
                            pointFormat: '{point.x:%e. %b}: {point.y:.2f}'
                        },

                        plotOptions: {
                            spline: {
                              marker: {
                                  enabled: true
                              }
                          }
                        },

                        series: [{
                            name: '当日上新',
                            data: data.onstock,
                        }, {
                            name: '当日上新产品销量',
                            data: data.usual,
                            visible: false
                        }]
                    });
                },
                error: function(){
                    alert("false");
                }
            });
            return false;
        });

        $('#form_test').submit(function(){
            var from_time = $("#test_from_time").val();
            var to_time = $("#test_to_time").val();
            var type = $("#hidden_test").val();

            $.ajax({
                type: "POST",
                data: {type:type,from_time:from_time,to_time:to_time},
                url: "{% url 'ajax_test' %}",
                cache: false,
                dataType: "html",

                success: function(data,statues,xml){
                    data = $.parseJSON(data);
                    console.log(data)
                    var seriesOptions = [],
                        seriesCounter = 0,
                        names = ['MSFT', 'AAPL', 'GOOG'];

                    /**
                     * Create the chart when all data is loaded
                     * @returns {undefined}
                     */
                    function createChart() {

                        Highcharts.stockChart('test', {

                            rangeSelector: {
                                selected: 4
                            },

                            yAxis: {
                                labels: {
                                    formatter: function () {
                                        return (this.value > 0 ? ' + ' : '') + this.value + '%';
                                    }
                                },
                                plotLines: [{
                                    value: 0,
                                    width: 2,
                                    color: 'silver'
                                }]
                            },

                            plotOptions: {
                                series: {
                                    compare: 'percent',
                                    showInNavigator: true
                                }
                            },

                            tooltip: {
                                pointFormat: '<span style="color:{series.color}">{series.name}</span>: <b>{point.y}</b> ({point.change}%)<br/>',
                                valueDecimals: 2,
                                split: true
                            },

                            series: seriesOptions
                        });
                    }
                    $.each(names, function (i, name) {
                        seriesOptions[i] = {
                            name: name,
                            data: data['data'+i]   
                        };
                        seriesCounter += 1;
                        if (seriesCounter === names.length) {
                            createChart();
                        }
                    });
                    
                },
                error: function(){
                    alert("false");
                }
            });
            return false;
        });
    });
</script>

<ul class="nav nav-tabs" role="tablist" id="myTab">
  <li role="presentation" class="active"><a href="#home" role="tab" data-toggle="tab">Home</a></li>
  <li role="presentation"><a href="#profile" role="tab" data-toggle="tab">Profile</a></li>
  <li role="presentation"><a href="#messages" role="tab" data-toggle="tab">Messages</a></li>
  <li role="presentation"><a href="#settings" role="tab" data-toggle="tab">Settings</a></li>
</ul>

<div class="tab-content">
  <div role="tabpanel" class="tab-pane active" id="home">...</div>
  <div role="tabpanel" class="tab-pane" id="profile">...</div>
  <div role="tabpanel" class="tab-pane" id="messages">...</div>
  <div role="tabpanel" class="tab-pane" id="settings">...</div>
</div>

<script>
  $(function () {
    $('#myTab a:first').tab('show')
  })
</script>





<script type="text/javascript">
    $('.date').cxCalendar();

    function selectAll(selelct_all,checkbox_name) {
        var obj = document.getElementById(selelct_all);
        var cks = document.getElementsByTagName("input");
        var ckslen = cks.length;
        if (obj.checked){
            for(var i=0;i<ckslen;i++) {
                if(cks[i].type == "checkbox" && cks[i].name==checkbox_name) {
                    cks[i].checked = true;
                }
            }
        }else{
            for(var i=0;i<ckslen;i++) {
                if(cks[i].type == "checkbox" && cks[i].name==checkbox_name) {
                    cks[i].checked = false;
                }
            }
        }
    }

    function submitForm(method){
        if(method == 'product_supplier_show'){
            document.getElementById('record').value = 'search';
            document.myFrom.submit();
        }
        if(method == 'product_supplier_export'){
            document.getElementById('record').value = 'export';
            document.myFrom.submit();
        }
    }
</script>
{% endblock %}

products/templates/attribute_by_skus.html
{% extends "base_header.html" %}
{% block content %}
{% include "cxcalendar.html" %}

<fieldset class="pro-sel">
<div class="sel-box">
    <table class="table table-hover">
        <tr>
            <td><strong>sku</strong></td>
            <td><strong>arrtibute</strong></td>
        </tr>

        {% for items in attributes %}
         <tr>
            <td>{{ items.sku }}</td>
            <td>{{ items.size }}</td>
        </tr>
        {% endfor %}

    </table>
</div>
</fieldset>
{% endblock %}

products/templates/export_cost.html
{% extends "base_header.html" %}
{% block content %}
{% include "cxcalendar.html" %}

<fieldset class="pro-sel">
<div class="sel-box">
    <table class="table table-hover">
        <tr>
            {% for i in header %}
            <td><strong>{{ i }}</strong></td>
            {% endfor%}
        </tr>
        {% for sku in skuarr %}
            {% for product in products %}
                {% if sku == product.sku %}
                    <tr>
                        <td>{{ product.sku }}</td>
                        <td>{{ product.price }}</td>
                        {% for key, value in sale_prices.items %}
                            {% if key == product.id %}
                                <td>{{ value }}</td>
                            {% endif %}
                        {% endfor %}
                        <td>{{ product.cost }}</td>
                        <td>{{ product.total_cost }}</td>
                        <td>{{ product.weight }}</td>
                    </tr>
                {% endif %}
            {% endfor %}
        {% endfor %}
    </table>
</div>
</div>
</fieldset>




<script type="text/javascript">
    $('.date').cxCalendar();

    function selectAll(selelct_all,checkbox_name) {
        var obj = document.getElementById(selelct_all);
        var cks = document.getElementsByTagName("input");
        var ckslen = cks.length;
        if (obj.checked){
            for(var i=0;i<ckslen;i++) {
                if(cks[i].type == "checkbox" && cks[i].name==checkbox_name) {
                    cks[i].checked = true;
                }
            }
        }else{
            for(var i=0;i<ckslen;i++) {
                if(cks[i].type == "checkbox" && cks[i].name==checkbox_name) {
                    cks[i].checked = false;
                }
            }
        }
    }

    function submitForm(method){
        if(method == 'product_supplier_show'){
            document.getElementById('record').value = 'search';
            document.myFrom.submit();
        }
        if(method == 'product_supplier_export'){
            document.getElementById('record').value = 'export';
            document.myFrom.submit();
        }
    }
</script>
{% endblock %}

products/templates/export_thumb.html
{% extends "base_header.html" %}
{% block content %}
{% include "cxcalendar.html" %}

<fieldset class="pro-sel">
<div class="sel-box">
    <table class="table table-hover">
        <tr>
            {% for i in hender %}
            <td><strong>{{ i }}</strong></td>
            {% endfor%}
        </tr>
        {% for sku in skuarr %}
            {% for product in products %}
                {% if sku == product.sku %}
                    <tr>
                        <td>{{ product.sku }}</td>
                        {% for key,value in images.items %}
                            {% if key == product.id %}
                                <td><image style="width: 100px;height: auto;" src="{{ value }}"/></td>
                            {% endif %}
                        {% endfor %}
                        <td>{{ product.offline_factory }}</td> <!-- 现价待处理 -->
                        <td>{{ product.offline_sku }}</td>
                        <td>{{ product.stock }}</td>
                    </tr>
                {% endif %}
            {% endfor %}
        {% endfor %}
    </table>
</div>
</div>
</fieldset>




<script type="text/javascript">
    $('.date').cxCalendar();

    function selectAll(selelct_all,checkbox_name) {
        var obj = document.getElementById(selelct_all);
        var cks = document.getElementsByTagName("input");
        var ckslen = cks.length;
        if (obj.checked){
            for(var i=0;i<ckslen;i++) {
                if(cks[i].type == "checkbox" && cks[i].name==checkbox_name) {
                    cks[i].checked = true;
                }
            }
        }else{
            for(var i=0;i<ckslen;i++) {
                if(cks[i].type == "checkbox" && cks[i].name==checkbox_name) {
                    cks[i].checked = false;
                }
            }
        }
    }

    function submitForm(method){
        if(method == 'product_supplier_show'){
            document.getElementById('record').value = 'search';
            document.myFrom.submit();
        }
        if(method == 'product_supplier_export'){
            document.getElementById('record').value = 'export';
            document.myFrom.submit();
        }
    }
</script>
{% endblock %}

products/templates/product_report_export.html
{% extends "base_header.html" %}
{% block content %}
{% include "cxcalendar.html" %}

<script type="text/javascript">
    $('.date').cxCalendar();

    function selectAll(selelct_all,checkbox_name) {
        var obj = document.getElementById(selelct_all);
        var cks = document.getElementsByTagName("input");
        var ckslen = cks.length;
        if (obj.checked){
            for(var i=0;i<ckslen;i++) {
                if(cks[i].type == "checkbox" && cks[i].name==checkbox_name) {
                    cks[i].checked = true;
                }
            }
        }else{
            for(var i=0;i<ckslen;i++) {
                if(cks[i].type == "checkbox" && cks[i].name==checkbox_name) {
                    cks[i].checked = false;
                }
            }
        }
    }

    function submitForm(method){
        if(method == 'product_supplier_show'){
            document.getElementById('record').value = 'search';
            document.myFrom.submit();
        }
        if(method == 'product_supplier_export'){
            document.getElementById('record').value = 'export';
            document.myFrom.submit();
        }
    }
</script>
{% endblock %}